/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "admin.events.index": [],
    "admin.events.create": [],
    "admin.events.store": [],
    "admin.events.edit": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.events.update": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.events.destroy": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.faqs.index": [],
    "admin.faqs.create": [],
    "admin.faqs.store": [],
    "admin.faqs.edit": [
        {
            "name": "faq",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.faqs.update": [
        {
            "name": "faq",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.faqs.destroy": [
        {
            "name": "faq",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.testimonials.index": [],
    "admin.testimonials.create": [],
    "admin.testimonials.store": [],
    "admin.testimonials.edit": [
        {
            "name": "testimonial",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.testimonials.update": [
        {
            "name": "testimonial",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.testimonials.destroy": [
        {
            "name": "testimonial",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "logout": [],
    "admin.dashboard": [],
    "admin.search.index": [],
    "admin.notifications.index": [],
    "admin.notifications.read": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.notifications.read-all": [],
    "admin.audit-log.index": [],
    "admin.cache.clear": [],
    "admin.modules.index": [],
    "admin.modules.enable": [
        {
            "name": "key",
            "required": true
        }
    ],
    "admin.modules.disable": [
        {
            "name": "key",
            "required": true
        }
    ],
    "admin.modules.reinstall": [
        {
            "name": "key",
            "required": true
        }
    ],
    "admin.modules.clear-health": [
        {
            "name": "key",
            "required": true
        }
    ],
    "admin.modules.toggle-nav": [
        {
            "name": "key",
            "required": true
        }
    ],
    "admin.modules.uninstall": [
        {
            "name": "key",
            "required": true
        }
    ],
    "admin.users.index": [],
    "admin.users.create": [],
    "admin.users.store": [],
    "admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.settings.index": [],
    "admin.settings.update": [],
    "admin.menus.index": [],
    "admin.menus.store": [],
    "admin.menus.update": [
        {
            "name": "menu",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.menus.destroy": [
        {
            "name": "menu",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.page-content.index": [],
    "admin.page-content.layout": [],
    "admin.page-content.update": [
        {
            "name": "file",
            "required": true
        }
    ],
    "admin.redirects.index": [],
    "admin.redirects.store": [],
    "admin.redirects.update": [
        {
            "name": "redirect",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.redirects.destroy": [
        {
            "name": "redirect",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.custom-code.index": [],
    "admin.custom-code.create": [],
    "admin.custom-code.store": [],
    "admin.custom-code.edit": [
        {
            "name": "customCode",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.custom-code.update": [
        {
            "name": "customCode",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.custom-code.toggle": [
        {
            "name": "customCode",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.custom-code.destroy": [
        {
            "name": "customCode",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.subscribers.index": [],
    "admin.subscribers.export": [],
    "admin.subscribers.destroy": [
        {
            "name": "subscriber",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.media.index": [],
    "admin.media.store": [],
    "admin.media.destroy": [
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.posts.index": [],
    "admin.posts.create": [],
    "admin.posts.store": [],
    "admin.posts.edit": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.posts.update": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.posts.destroy": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.index": [],
    "admin.categories.create": [],
    "admin.categories.store": [],
    "admin.categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tags.index": [],
    "admin.tags.store": [],
    "admin.tags.update": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tags.destroy": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.index": [],
    "admin.products.create": [],
    "admin.products.store": [],
    "admin.products.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.index": [],
    "admin.orders.show": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.update-status": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.careers.index": [],
    "admin.careers.create": [],
    "admin.careers.store": [],
    "admin.careers.edit": [
        {
            "name": "career",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.careers.update": [
        {
            "name": "career",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.careers.destroy": [
        {
            "name": "career",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.case-studies.index": [],
    "admin.case-studies.create": [],
    "admin.case-studies.store": [],
    "admin.case-studies.edit": [
        {
            "name": "case_study",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.case-studies.update": [
        {
            "name": "case_study",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.case-studies.destroy": [
        {
            "name": "case_study",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.teams.index": [],
    "admin.teams.create": [],
    "admin.teams.store": [],
    "admin.teams.edit": [
        {
            "name": "team",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.teams.update": [
        {
            "name": "team",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.teams.destroy": [
        {
            "name": "team",
            "required": true,
            "binding": "id"
        }
    ],
    "home": [],
    "about": [],
    "sitemap": [],
    "robots": [],
    "contact": [],
    "contact.store": [],
    "newsletter.store": [],
    "profile.show": [],
    "profile.update": [],
    "page.show": [
        {
            "name": "page",
            "required": true,
            "binding": "slug"
        }
    ],
    "blog.index": [],
    "blog.show": [
        {
            "name": "post",
            "required": true,
            "binding": "slug"
        }
    ],
    "shop.index": [],
    "shop.show": [
        {
            "name": "product",
            "required": true,
            "binding": "slug"
        }
    ],
    "cart.show": [],
    "cart.add": [],
    "cart.update": [],
    "cart.remove": [
        {
            "name": "productId",
            "required": true
        }
    ],
    "checkout.show": [],
    "checkout.store": [],
    "order.confirmation": [
        {
            "name": "orderNumber",
            "required": true
        }
    ],
    "careers.index": [],
    "careers.show": [
        {
            "name": "career",
            "required": true,
            "binding": "slug"
        }
    ],
    "case-studies.index": [],
    "case-studies.show": [
        {
            "name": "caseStudy",
            "required": true,
            "binding": "slug"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
